project:
  name: quickstart-linux-utilities
   owner: tonynv@amazon.com
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-2
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  ubuntu18:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      BucketRegion: $[taskcat_current_region]
      GitRepo: https://github.com/aws-quickstart/quickstart-linux-utilities.git
      KeyPairName: cikey
      TestAMIOS: Ubuntu-Server-18.04-LTS-HVM
    regions:
    - us-east-2
    template: templates/ci_test-master.template.yaml
  ubuntu20:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      BucketRegion: $[taskcat_current_region]
      GitRepo: https://github.com/aws-quickstart/quickstart-linux-utilities.git
      KeyPairName: cikey
      TestAMIOS: Ubuntu-Server-20.04-LTS-HVM
    regions:
    - us-east-2
    template: templates/ci_test-master.template.yaml
  amzn2:
    parameters:
      AccessCIDR: 0.0.0.0/0
      AvailabilityZones: $[taskcat_getaz_2]
      BucketName: $[taskcat_autobucket]
      BucketRegion: $[taskcat_current_region]
      GitRepo: https://github.com/aws-quickstart/quickstart-linux-utilities.git
      KeyPairName: cikey
      TestAMIOS: Amazon-Linux2-HVM
    regions:
    - us-east-2
    template: templates/ci_test-master.template.yaml
      centos7:
        parameters:
          AccessCIDR: 0.0.0.0/0
          AvailabilityZones: $[taskcat_getaz_2]
          BucketName: $[taskcat_autobucket]
          BucketRegion: $[taskcat_current_region]
          GitRepo: https://github.com/aws-quickstart/quickstart-linux-utilities.git
          KeyPairName: cikey
          TestAMIOS: CentOS-7-HVM
        regions:
        - us-east-2
        template: templates/ci_test-master.template.yaml
