AWSTemplateFormatVersion: 2010-09-09
Description: "CI Stack for Linux Utils"
Metadata:
  LICENSE: 'Apache License, Version 2.0' 
  AUTHOR: 'Tony Vattathil'
  EMAIL: 'tonynv@amazon.com'
Parameters:
  TestAMIOS:
    AllowedValues:
      - Amazon-Linux2-HVM
      - Amazon-Linux-HVM
      - CentOS-7-HVM
      - Ubuntu-Server-14.04-LTS-HVM
      - Ubuntu-Server-16.04-LTS-HVM
      - Ubuntu-Server-18.04-LTS-HVM
      - SUSE-SLES-15-HVM
    Default: Amazon-Linux2-HVM
    Description: The Linux distribution for the AMI to be used for the bastion instances.
    Type: String
  AccessCIDR:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: The IP address range that can be used to access to the EC2 instance
    MaxLength: '18'
    MinLength: '9'
    Type: String
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: id_rsa_aws
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  SubnetId:
    Description: The Public subnet where the ec2 instance will be launched
    Type: AWS::EC2::Subnet::Id
  VPCID:
    Description: VPC 1D
    Type: AWS::EC2::VPC::Id
  BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: 'replace-with-your-staging-bucket'
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-linux-utilities/
    Description: >-
      S3 key prefix where assets are located should end withforward slash (/).
    Type: String
  GitRepo:
    Default: https://github.com/aws-quickstart/quickstart-linux-utilities.git
    Type: String
  GitBranch:
    Default: develop
    Type: String
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      AMZNLINUX2: ami-011facbea5ec0363b
      AMZNLINUXHVM: ami-079e6fb1e856e80c1
      CENTOS7HVM: ami-045f38c93733dd48d
      US1604HVM: ami-018e83eeb86cbe915
      US1804HVM: ami-07f4cb4629342979c
      SLES15HVM: ami-056ac8ad44e6a7e1f
    ap-northeast-2:
      AMZNLINUX2: ami-0bea7fd38fabe821a
      AMZNLINUXHVM: ami-0e4a253fb5f082688
      CENTOS7HVM: ami-06cf2a72dadf92410
      US1604HVM: ami-025376d8670c1a73f
      US1804HVM: ami-0cd7b0de75f5a35d1
      SLES15HVM: ami-0f81fff879bafe6b8
    ap-south-1:
      AMZNLINUX2: ami-0217a85e28e625474
      AMZNLINUXHVM: ami-01e074f40dfb9999d
      CENTOS7HVM: ami-02e60be79e78fef21
      US1604HVM: ami-0979cb27961aadbf7
      US1804HVM: ami-0620d12a9cf777c87
      SLES15HVM: ami-01be89269d32f2a16
    ap-southeast-1:
      AMZNLINUX2: ami-05c64f7b4062b0a21
      AMZNLINUXHVM: ami-0d9233e8ce73df7b2
      CENTOS7HVM: ami-0b4dd9d65556cac22
      US1604HVM: ami-0216473266cb8902d
      US1804HVM: ami-09a4a9ce71ff3f20b
      SLES15HVM: ami-070356c21596ddc67
    ap-southeast-2:
      AMZNLINUX2: ami-0b8b10b5bf11f3a22
      AMZNLINUXHVM: ami-0c91f97cadcc8499e
      CENTOS7HVM: ami-08bd00d7713a39e7d
      US1604HVM: ami-04dc124dae2db71ce
      US1804HVM: ami-02a599eb01e3b3c5b
      SLES15HVM: ami-0c4245381c67efb39
    ca-central-1:
      AMZNLINUX2: ami-0a269ca7cc3e3beff
      AMZNLINUXHVM: ami-003a0ba7ea76b2785
      CENTOS7HVM: ami-033e6106180a626d0
      US1604HVM: ami-038c40a61ea4741d9
      US1804HVM: ami-098dce2d49ef14294
      SLES15HVM: ami-0c97d9b588207dad6
    eu-central-1:
      AMZNLINUX2: ami-07cda0db070313c52
      AMZNLINUXHVM: ami-0ab838eeee7f316eb
      CENTOS7HVM: ami-04cf43aca3e6f3de3
      US1604HVM: ami-0e0104f9044920d13
      US1804HVM: ami-0b418580298265d5c
      SLES15HVM: ami-05dfd265ea534a3e9
    eu-north-1:
      AMZNLINUX2: ami-0662eb9b9b8685935
      AMZNLINUXHVM: ami-0f1d8c8ad70ce9c62
      CENTOS7HVM: ami-5ee66f20
      US1604HVM: ami-0b47beea55400168b
      US1804HVM: ami-0b7937aeb16a7eb94
      SLES15HVM: ami-0741fa1a008af40ad
    eu-west-1:
      AMZNLINUX2: ami-0713f98de93617bb4
      AMZNLINUXHVM: ami-071f4ce599deff521
      CENTOS7HVM: ami-0ff760d16d9497662
      US1604HVM: ami-0b508e9b54730f606
      US1804HVM: ami-035966e8adab4aaad
      SLES15HVM: ami-0a58a1b152ba55f1d
    eu-west-2:
      AMZNLINUX2: ami-0089b31e09ac3fffc
      AMZNLINUXHVM: ami-0e49551fc78560451
      CENTOS7HVM: ami-0eab3a90fc693af19
      US1604HVM: ami-0a99b53e387548f98
      US1804HVM: ami-006a0174c6c25ac06
      SLES15HVM: ami-01497522185aaa4ee
    eu-west-3:
      AMZNLINUX2: ami-007fae589fdf6e955
      AMZNLINUXHVM: ami-0ec1d48c59dda554a
      CENTOS7HVM: ami-0e1ab783dc9489f34
      US1604HVM: ami-0a5f39196a2cf5c4a
      US1804HVM: ami-096b8af6e7e8fb927
      SLES15HVM: ami-0f238bd4c6fdbefb0
    sa-east-1:
      AMZNLINUX2: ami-09de7b4017733e2af
      AMZNLINUXHVM: ami-04b202bf877b5027b
      CENTOS7HVM: ami-0b8d86d4bf91850af
      US1604HVM: ami-0b2044c8d1b29388f
      US1804HVM: ami-05494b93950efa2fd
      SLES15HVM: ami-0772af912976aa692
    us-east-1:
      AMZNLINUX2: ami-062f7200baf2fa504
      AMZNLINUXHVM: ami-09d069a04349dc3cb
      CENTOS7HVM: ami-02eac2c0129f6376b
      US1604HVM: ami-0bfb5f753b6c2d30b
      US1804HVM: ami-07ebfd5b3428b6f4d
      SLES15HVM: ami-0b1764f3d7d2e2316
    us-east-2:
      AMZNLINUX2: ami-02ccb28830b645a41
      AMZNLINUXHVM: ami-0d542ef84ec55d71c
      CENTOS7HVM: ami-0f2b4fc905b0bd1f1
      US1604HVM: ami-0bf3d772090752dc5
      US1804HVM: ami-0fc20dd1da406780b
      SLES15HVM: ami-05ea824317ffc0c20
    us-west-1:
      AMZNLINUX2: ami-03caa3f860895f82e
      AMZNLINUXHVM: ami-04bc3da8f14823e88
      CENTOS7HVM: ami-074e2d6769f445be5
      US1604HVM: ami-086be1694c3196bfb
      US1804HVM: ami-03ba3948f6c37a4b0
      SLES15HVM: ami-00e34a7624e5a7107
    us-west-2:
      AMZNLINUX2: ami-04590e7389a6e577c
      AMZNLINUXHVM: ami-01460aa81365561fe
      CENTOS7HVM: ami-01ed306a12b7d1c96
      US1604HVM: ami-06c94f9acb4ba21b2
      US1804HVM: ami-0d1cd67c26f5fca19
      SLES15HVM: ami-0f1e3b3fb0fec0361
  LinuxAMINameMap:
    Amazon-Linux2-HVM:
      Code: AMZNLINUX2
    Amazon-Linux-HVM:
      Code: AMZNLINUXHVM
    CentOS-7-HVM:
      Code: CENTOS7HVM
    Ubuntu-Server-18.04-LTS-HVM:
      Code: US1804HVM
    Ubuntu-Server-16.04-LTS-HVM:
      Code: US1604HVM
    SUSE-SLES-15-HVM:
      Code: SLES15HVM
Conditions:
  GovCloudCondition: !Equals
    - !Ref AWS::Region
    - us-gov-west-1
Resources:
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ec2.amazonaws.com
            Effect: Allow
            Sid: ''
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${BucketName}/${KeyPrefix}*'
                Effect: Allow
          PolicyName: AuthenticatedS3GetObjects
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  InstanceSecurityGroup:
    Properties:
      GroupDescription: 'ssh access to instance'
      SecurityGroupIngress:
        - CidrIp: !Ref AccessCIDR
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref VPCID
    Type: 'AWS::EC2::SecurityGroup'
  LinuxInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      IamInstanceProfile: !Ref RootInstanceProfile
      ImageId: !FindInMap 
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - !FindInMap 
          - LinuxAMINameMap
          - !Ref TestAMIOS
          - Code
      InstanceType: t2.large
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref SubnetId
      UserData: !Base64
          Fn::Sub: 
          - |
            #!/bin/bash -x
            #cfn signaling functions
            echo "[INFO] Start UserData in ${S3Region}";
            yum install git -y || apt-get install -y git

            function cfn_fail
            {
              cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource LinuxInstance
              exit 1
            }

            function cfn_success
            {
              cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource LinuxInstance
              exit 0
            }

            until git clone -b ${GitBranch} ${GitRepo} ; do echo "Retrying"; done
            cd /quickstart-linux-utilities;
            source quickstart-cfn-tools.source;
            qs_update-os || qs_err;
            #qs_bootstrap_pip || qs_err " pip bootstrap failed ";
            qs_aws-cfn-bootstrap || qs_err " cfn bootstrap failed ";
            echo "[INFO] Executing config-sets";
            cfn-init -v --stack ${AWS::StackName} --resource LinuxInstance --configsets ec2_bootstrap --region ${AWS::Region} || cfn_fail;
            qs_status;
            [ $(qs_status) == 0 ] && cfn_success || cfn_fail "signaled"
          -
            S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
    Metadata:
      AWS::CloudFormation::Authentication: 
        S3AccessCreds: 
          type: S3
          buckets: 
            - !Sub ${BucketName}
          roleName: 
            Ref: RootRole
      AWS::CloudFormation::Init:
        configSets:
          ec2_bootstrap:
            - helloworld_cfg
        helloworld_cfg:
          commands:
            010_hello:
              command: /tmp/bootstrap.sh 'hello world'
          files:
            /tmp/bootstrap.sh:
              source: !Sub
                - >-
                  https://${BucketName}.${S3Region}.amazonaws.com/${KeyPrefix}scripts/print_stdout.sh
                - BucketName: !Ref BucketName
                  S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
                  KeyPrefix: !Ref KeyPrefix
              mode: '000755'
              owner: root
              group: root
              authentication: S3AccessCreds
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT20M
